# Generated by Django 3.2 on 2023-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='status',
            field=models.CharField(blank=True, choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=15, null=True),
        ),
    ]
