# Generated by Django 4.1.3 on 2022-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
