# Generated by Django 4.1.2 on 2022-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
