# Generated by Django 4.1.2 on 2022-10-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
