# Generated by Django 4.1.2 on 2022-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_gig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='Deadline',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
