# Generated by Django 3.2 on 2022-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
