# Generated by Django 4.1.2 on 2022-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_deadline_gig_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
