# Generated by Django 4.1.2 on 2022-10-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Price',
            new_name='price',
        ),
    ]
