# Generated by Django 3.2 on 2022-12-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.writer'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
