# Generated by Django 4.1.2 on 2022-10-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_contact_rename_price_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
