# Generated by Django 3.2 on 2022-12-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_writer_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='writer',
            new_name='user',
        ),
    ]
