# Generated by Django 3.2 on 2022-12-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_writer_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
