# Generated by Django 3.2 on 2022-12-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_user_account_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='writer',
            new_name='user',
        ),
    ]
