# Generated by Django 4.1.3 on 2022-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_writer_code_writer_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
