# Generated by Django 4.1.3 on 2022-11-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_writer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='code',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
    ]
